# Манифест развертывания задачи на CTFd
# Полный пример можно посмотреть в документации -- https://github.com/CTFd/ctfcli/blob/master/ctfcli/spec/challenge-example.yml
# Необязательные, но нужные вам секции можно раскомментировать

# Обязательные поля
# Имя задачи на CTFd
name: Train
# Никнейм в Telegram
author: "@kahiroomba"
# Описание таска на платформе.
description: |
  `@kahiroomba`

  > Эксперимент 052-1: 23 июня 2022. Агент ████ вошел в поезд. Следы найдены в 1935 году.
  >
  > Эксперимент 052-2: 16 февраля 2023. Агент ██████ вошел в поезд. Следы найдены в 1982 году, агент погиб по прибытии.
  >
  > Эксперимент 052-3: 26 марта 2023. Агент █████ вошел в поезд. Следов не найдено.

  `@scp_052_ctf_bot`

# Одна из следующих категорий: web, reverse, pwn, osint, joy, forensic, stegano, crypto
category: osint
# Оставляем как есть - цена таски
value: 100
# Не трогаем - тип соревнования
type: dynamic

extra:
    # Стартовая цена
    initial: 100
    # Сколько команд должны решить, чтобы цена упала до минимума
    decay: 20
    # Минимальная цена
    minimum: 10

# Опциональные настройки, включайте по мере необходимости
# Коннект к удаленной машине, может быть nc или URL к сайту
# connection_info: nc hostname 12345

# Флаги. Их может быть очень много, но обычно делают один
flags:
  # Нечувствительный к регистру флаг
  - {
    type: "static",
    content: "vrnctf{w3lcome_to_t1me_an0mali3es_ag3nt}",
    data: "case_insensitive",
  }

# Примечания для админов, не видны участникам
# Разрешены строки

# topics:
#   - information disclosure
#   - buffer overflow
#   - memory forensics

# Публичны, видят участники. Можно вешать теги на задачи
# tags:
#   - web
#   - sandbox
#   - js

# Секция с файликами, которые отдаются участниками. Относительный путь от папки public
# files:
#   - public/task.osz

# Подсказки. Можно передавать словари и строки
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# Если у вас задача зависит от другой, и не должна быть сдана до того, как решат первую - можно так сделать
# requirements:
#     - "Warmup"
#     - "Are you alive"

# Отображение на платформе. visible/hidden
state: visible
# Версия вашей задачи
version: "0.1"
